onlinecourses/Projeto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')),
    path('cursos/', include('cursos.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourses/cursos/urls.py
from django.urls import include, path
from . import views

app_name = 'cursos'
urlpatterns = [
# /cursos/
     path("", views.index, name='index'),
# /cursos/profile
     path("profile", views.profile, name='profile'),
#pagina login
     path('login', views.loginview, name='login'),
#efetuar logout
     path('logout', views.logoutview, name='logout'),
# /cursos/registar
     path("registar", views.registar, name='registar'),
# /cursos/meuscursos
     path("meuscursos", views.meuscursos, name='meuscursos'),
# ex: /cursos/1
     path('<int:curso_id>', views.detalhe,name='detalhe'),
# ex: /cursos/1/pagamento
     path('<int:curso_id>/pagamento', views.pagamento,name='pagamento'),
# ex: /cursos/search
     path('search', views.search, name='search'),
# ex: /cursos/1/compra
     path('<int:curso_id>/compra', views.compra,name='compra'),
# ex: /cursos/becometeacher
     path('becometeacher', views.becometeacher, name='becometeacher'),
# ex: /cursos/apply
     path('apply', views.apply, name='apply'),
# ex: /cursos/applications
     path('applications', views.applications, name='applications'),
# ex: /cursos/send_email/1
     path('send_email/<int:application_id>/', views.send_email, name='send_email'),
# ex: /cursos/delapplication/1
     path('delapplication/<int:application_id>/', views.delapplication, name='delapplication'),
# ex: /cursos/manageprofessors
     path('manageprofessors', views.manageprofessors, name='manageprofessors'),
# ex: /cursos/manageusers
     path('createprof', views.createprof, name='createprof'),
# ex: /cursos/manageusers
     path('deleteprof', views.deleteprof, name='deleteprof'),
# ex: /cursos/criarcurso
     path('criarcurso', views.criarcurso, name='criarcurso'),
# ex: /cursos/submitcurso
     path('submitcurso', views.submitcurso, name='submitcurso'),
# ex: /cursos/deletecurso/1
     path('deletecurso/<int:curso_id>/', views.deletecurso, name='deletecurso'),
]

onlinecourses/main/urls.py
from django.urls import include, path
from . import views

app_name = 'main'
urlpatterns = [

    path("", views.home, name='home'),


]

onlinecourses/onlinecourses/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

onlinecourses/cursos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Utilizador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    image = models.ImageField(upload_to='profile_image', default='defaultuser.png', null=True, blank=True)


class Professor(models.Model):
    Utilizador = models.OneToOneField(Utilizador, on_delete=models.CASCADE)
    area = models.CharField(max_length=30)
    email = models.EmailField(unique=True)

    def is_same_area(self, nome_area):
        return self.area == nome_area

class Curso(models.Model):
    descricao = models.CharField(max_length=100)
    area = area = models.CharField(max_length=30)
    vendas = models.IntegerField(default=0)
    data_publicamento = models.DateTimeField(default=timezone.now)
    preco = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to='curso_image/', default='defaultcourse.png')
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)

class Cliente(models.Model):
    Utilizador = models.OneToOneField(Utilizador, on_delete=models.CASCADE)
    ocupacao = models.CharField(max_length=30)

#Necessário porque é uma relação muitos para muitos entre cliente e curso
class Compra(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    data_compra = models.DateTimeField(default=timezone.now)
    num_cartao = models.IntegerField(max_length=16)
    dat_expir = models.DateTimeField(default=timezone.now())
    cvv = models.IntegerField(max_length=3)

class Application(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    area_of_expertise = models.CharField(max_length=100)
    certification = models.FileField(upload_to='certifications/')
    approved = models.BooleanField(default=False)


class Content(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    file = models.FileField(upload_to='contents/')

onlinecourses/cursos/views.py
from django.contrib.auth.decorators import *
from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.http import Http404, HttpResponse,HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login , logout
from django.template import loader
from .models import Curso, Professor, Utilizador, User, Compra, Cliente, Application, Content
from django.contrib import messages
from django.core.files.storage import FileSystemStorage

#mostra pagina inicial
def index(request):
    return render(request, 'cursos/index.html')

#funcao auxiliar que verifica se user -> admin
def check_superuser(user):
    return user.is_superuser

def check_professor(user):
    return user.is_authenticated and not user.is_superuser and hasattr(user.utilizador, 'professor')


def search(request):
    query = request.GET.get('q')
    cursos = Curso.objects.filter(Q(descricao__icontains=query))
    return render(request, 'cursos/search_results.html', {'cursos': cursos})

@login_required(login_url=reverse_lazy('cursos:login'))
def detalhe(request, curso_id):
    curso = get_object_or_404(Curso, pk=curso_id)
    conteudos = Content.objects.filter(curso=curso)
    vendas = Compra.objects.filter(curso=curso).count()
    if not check_superuser(request.user) and not check_professor(request.user):

        cliente = request.user.utilizador.cliente
        compra = Compra.objects.filter(cliente=cliente, curso=curso).first()
        if compra is None:
            return redirect('cursos:pagamento', curso_id=curso.id)
    return render(request, 'cursos/detalhe.html', {'curso': curso, 'conteudos': conteudos,'vendas': vendas})

@login_required(login_url=reverse_lazy('cursos:login'))
def compra(request, curso_id):
    curso = get_object_or_404(Curso, pk=curso_id)
    if request.method == 'POST':
        card_number = request.POST.get('cardNumber')
        card_number_without_space = card_number.replace(" ", "")
        card_number_int = int(card_number_without_space)
        card_name = request.POST.get('cardName')
        expiry_month = request.POST.get('expiryMonth')
        expiry_year = request.POST.get('expiryYear')
        cvv = request.POST.get('cvv')
        cliente = Cliente.objects.get(Utilizador=request.user.utilizador)
        compra = Compra.objects.create(
            cliente=cliente,
            curso=curso,
            data_compra=timezone.now(),
            num_cartao=card_number_int,
            dat_expir=timezone.datetime(int(expiry_year), int(expiry_month), 1).replace(day=28) + timezone.timedelta(
                days=3),
            cvv=cvv,
        )
        compra.save()
        return HttpResponseRedirect(reverse('cursos:detalhe', args=(curso_id,)))

@user_passes_test(check_superuser, login_url=reverse_lazy('cursos:login'))
def applications(request):
    applications = Application.objects.filter(approved=False)
    return render(request,'cursos/applications.html',{'applications': applications})
@user_passes_test(check_superuser, login_url=reverse_lazy('cursos:login'))
def send_email(request, application_id):
    application = get_object_or_404(Application, pk=application_id)
    application.approved = True
    application.save()
    send_mail(
        'Application',
        'Your application has been accepted! Please get back to us and let us know which username and password combination you would like.',
        'bestecourses.recruitment@gmail.com',
        [application.email],
        fail_silently=False,
    )
    return HttpResponseRedirect(reverse('cursos:applications'))
@user_passes_test(check_superuser, login_url=reverse_lazy('cursos:login'))
def delapplication(request, application_id):
    application = get_object_or_404(Application, pk=application_id)
    application.delete()
    return HttpResponseRedirect(reverse('cursos:applications'))

@user_passes_test(check_superuser, login_url=reverse_lazy('cursos:login'))
def manageprofessors(request):
    return render(request, 'cursos/manageprofessors.html')



def apply(request):
    if request.method == 'POST' and request.FILES['myfile']:

        prim_nome = request.POST.get('primnome')
        ult_nome = request.POST.get('ultnome')
        email = request.POST.get('email')
        numero = request.POST.get('numero')
        area = request.POST.get('area')
        file = request.FILES['myfile']



        application = Application(
            first_name=prim_nome,
            last_name=ult_nome,
            email=email,
            phone_number=numero,
            area_of_expertise=area,
            certification=file,
        )
        application.save()

        # Redirect to success page
        return HttpResponseRedirect(reverse('cursos:index'))

        # Render the application page
    return render(request, 'cursos/becometeacher.html')

def becometeacher(request):
    return render(request, 'cursos/becometeacher.html')

def loginview(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('cursos:index'))
        else:
            return render(request, 'cursos/login.html', {
                'error_message': "Wrong username/password", })

    return render(request, 'cursos/login.html')

@login_required(login_url=reverse_lazy('cursos:login'))
def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('cursos:login'))

@login_required(login_url=reverse_lazy('cursos:login'))
def pagamento(request, curso_id):
    if not check_superuser(request.user):
        curso = get_object_or_404(Curso, pk=curso_id)
        return render(request, 'cursos/pagamento.html',{'curso': curso})
    else:
        return render(request, 'cursos/login.html', {
            'error_message': "This content is for clients only", })

def registar(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        if User.objects.filter(email=email).exists():
            return render(request, 'cursos/registar.html', {'error_message': 'A user with that email already exists.'})
        u = User.objects.create_user(username, email, password)
        utilizador = Utilizador(user=u)
        utilizador.save()
        cliente = Cliente(Utilizador=utilizador)
        cliente.save()

        return HttpResponseRedirect(reverse('cursos:login'))
    else:
        return render(request, 'cursos/registar.html')


@login_required(login_url=reverse_lazy('cursos:login'))
def meuscursos(request):
    if not request.user.is_superuser:
        if request.user.utilizador.cliente:
            cliente = request.user.utilizador.cliente
            cursos_comprados = Curso.objects.filter(compra__cliente=cliente)
            cursos = Curso.objects.all()
            return render(request, 'cursos/meuscursos.html', {'cursos': cursos_comprados})
    else:
        return render(request, 'cursos/login.html', {
            'error_message': "This content is for clients only", })

@user_passes_test(check_professor, login_url=reverse_lazy('cursos:login'))
def criarcurso(request):
    return render(request,'cursos/criarcursos.html')

@user_passes_test(check_professor, login_url=reverse_lazy('cursos:login'))
def submitcurso(request):
    if request.method == 'POST':
        # get the data submitted in the form
        descricao = request.POST['descricao']
        preco = request.POST['preco']
        image = request.FILES.get('image')
        titulos_conteudos = request.POST.getlist('titulo_conteudo[]')
        arquivos = request.FILES.getlist('conteudo[]')
        area = request.user.utilizador.professor.area
        if image is None:
            curso = Curso.objects.create(descricao=descricao, professor=request.user.utilizador.professor, preco=preco,area=area)
        else:
            curso = Curso.objects.create(descricao=descricao, professor=request.user.utilizador.professor, preco=preco,
                                         image=image,area=area)

        # create Conteudo instances and add them to the curso
        for i in range(len(titulos_conteudos)):
            titulo_conteudo = titulos_conteudos[i]
            arquivo = arquivos[i]
            conteudo = Content.objects.create(title=titulo_conteudo, file=arquivo,curso=curso)
            conteudo.save()

        # redirect to the newly created curso
        return redirect('cursos:index')

    return render(request, 'cursos/criarcurso.html')

@login_required(login_url=reverse_lazy('cursos:login'))
def profile(request):
    return render(request,'cursos/profile.html')

#admin cria um professor(so o admin pode registar um professor)
@user_passes_test(check_superuser, login_url=reverse_lazy('cursos:login'))
def createprof(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['emailcreate']
        application = Application.objects.filter(email=email).first()
        if application:
            area = application.area_of_expertise
            u = User.objects.create_user(username, email, password)
            utilizador = Utilizador(user=u)
            utilizador.save()
            prof = Professor.objects.create(Utilizador=utilizador,area=area,email=email)
            prof.save()
            messages.success(request, 'Professor created successfully!')
            return redirect('cursos:manageprofessors')
        else:
            return render(request, 'cursos/manageprofessors.html', {
                    'error_message': "No application for this email!", })
    else:

onlinecourses/cursos/templates/cursos/applications.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "./base.html" %}
{% block conteudo%}
{% for application in applications %}
<div class="application-card">
        <h2 class="text-white">{{ application.first_name }} {{ application.last_name }}</h2>
        <p class="text-white"><strong>Email:</strong> {{ application.email }}</p>
        <p class="text-white"><strong>Phone Number:</strong> {{ application.phone_number }}</p>
        <p class="text-white"><strong>Area of Expertise:</strong> {{ application.area_of_expertise }}</p>
        <p class="text-white"><strong>Certification:</strong> <a href="{{ application.certification.url }}">{{ application.certification.name }}</a></p>
         <a href="{% url 'cursos:send_email' application.id %}"><button>Accept</button></a>
        <a href="{% url 'cursos:delapplication' application.id %}"><button>Revoke</button></a>
</div>


{% endfor %}

{% endblock %}
</body>
</html>

onlinecourses/cursos/templates/cursos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cursos</title>
     {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'cursos/css/style.css' %}">

</head>
<body>
{% block topo%}
    <header> <!-- inicio Cabecalho -->
      <nav class="navbar navbar-expand-md navbar-light navbar-transparente ">
        <div class="container">






         <a class="navbar-brand">
            <img src="../../../static/cursos/images/logo.png" alt="Logo" style="width:250px;">
        </a>


           <form class="form-inline " action="{% url 'cursos:search' %}" method="get">
                <input type="text"  class="form-control mr-sm-2"  name="q" placeholder="Search">
                <button class="btn btn-success"  type="submit">Go</button>
                </form>

          <div>
              <ul class="navbar-nav ml-auto">

                  <li class="nav-item">
                <a href="{% url 'cursos:index' %}" class="nav-link">Home</a>
              </li>
{% if not user.is_superuser %}
    {% if user.utilizador.professor %}
                <li class="nav-item">
                    <a href="{% url 'cursos:criarcurso' %}" class="nav-link">New Course</a>
                </li>
    {% else %}
                  <li class="nav-item">
                <a href="{% url 'cursos:becometeacher' %}" class="nav-link">Be a teacher</a>
                      </li>
    {% endif %}
{% else %}
             <li class="nav-item">
                <a href="{% url 'cursos:applications' %}" class="nav-link">Applications</a>
                      </li>
            <li class="nav-item">
                <a href="{% url 'cursos:manageprofessors' %}" class="nav-link">Professors</a>
                      </li>
{% endif %}

{% if user.is_authenticated %}
               <li class="nav-item">
                <a href="{% url 'cursos:profile' %}" class="nav-link">Profile</a>
              </li>
{% if request.user.utilizador.cliente %}
      <li class="nav-item">
                <a href="{% url 'cursos:meuscursos' %}" class="nav-link">My courses</a>
              </li>
{% endif %}
      <li class="nav-item">
                <a href="{% url 'cursos:logout' %}" class="nav-link">Logout</a>
              </li>


              <li class="nav-item divisor">

              </li>
{% else %}

               <li class="nav-item">
                <a href="{% url 'cursos:login' %}" class="nav-link">Login</a>
              </li>

               <li class="nav-item">
                <a href="{% url 'cursos:registar' %}" class="nav-link">Register</a>
              </li>
{% endif %}



            </ul>

          </div>
        </div>
      </nav>


    </header>  <!-- fim Cabecalho -->


{% endblock %}
{% block conteudo %}
Conteudo
{% endblock %}




</body>
</html>

onlinecourses/cursos/templates/cursos/becometeacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "./base.html" %}
{% block conteudo%}
<div class="container_login">
    <h2 class="text-white">Insert your personal data</h2>
    <form enctype="multipart/form-data" action="{% url 'cursos:apply' %}"
    method="post">
    {% csrf_token %}
        <label for="primnome"> First name:</label>
        <input type="text" id="primnome" name="primnome" required/><br>
        <label for="ultnome">  Last name:</label>
        <input type="text" id="ultnome" name="ultnome" required/><br>
        <label for="Email"> Email:</label>
        <input type="text" id="Email" name="email" required/><br>
        <label for="numero"> Phone number:</label>
        <input type="number" id="numero" name="numero" required/><br>
        <label for="area"> Area of expertis:</label>
        <input type="text" id="area" name="area" required/><br>
        <label for="area"> Certification:</label>
        <input type="file" id="myfile" name="myfile" required><br>

    <input type="submit" value="Submit" />
    </form>
</div>

{% endblock %}
</body>
</html>

onlinecourses/cursos/templates/cursos/criarcursos.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Criar Curso</title>
</head>
<body>

{% extends "./base.html" %}
{% block conteudo%}
<div class="container">
  <h1>Create Course</h1>

  <div class="form-group">
    <form method="POST" action="{% url 'cursos:submitcurso' %}" enctype="multipart/form-data">
      {% csrf_token %}
      <label  for="descricao">Description</label>
      <input  class="form-control col-6" type="text" id="descricao" name="descricao" required>
       <br>
      <label for="preco">Price</label>
      <input  class="form-control  col-6" type="number" id="preco" name="preco"  step="any" required>
      <br>
      <label  for="image">Image(optional)</label>
      <input  class=" row col-6" type="file" id="image" name="image">
      <h2 style="color:white">Contents</h2>
      <div id="conteudos">

          <label for="titulo-conteudo">Title</label>
          <input  class="form-control col-6"  type="text" id="titulo-conteudo" name="titulo_conteudo[]" required>
          <label class=" mt-2" for="conteudo">Content</label>
          <input  class=" row col-6"  type="file" id="conteudo" name="conteudo[]" required>
          <br>
      </div>
    <div class="col-6">
      <button   type="button" onclick="adicionarConteudo()" class="form-button col-4">Add contents</button>
      <br><br>
      <button  type="submit" class= "form-button col-4">Create Course</button>
    </div>

    </form>

  </div>
</div>

  <script>
    function adicionarConteudo() {
      var conteudos = document.getElementById("conteudos");
      var conteudo = document.createElement("div");

      conteudo.innerHTML = '<label for="titulo-conteudo">Title</label>' +
                            '<input  class="form-control col-6"  type="text" id="titulo-conteudo" name="titulo_conteudo[]" required>' +
                            '<label for="conteudo">Content</label>' +
                            '<input  class="col-6 mt-2"  type="file" id="conteudo" name="conteudo[]" required>' +
                            '<br>';
      conteudos.appendChild(conteudo);
    }
  </script>
{% endblock %}
</body>
</html>

onlinecourses/cursos/templates/cursos/detalhe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "./base.html" %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6">
      {% if request.user.is_superuser %}
      <form method="POST" action="{% url 'cursos:deletecurso' curso.pk %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete Course</button>
      </form>
      {% endif %}

        <h1 class="text-white">{{ curso.descricao }}</h1>
        <p class="text-white">Price:{{ curso.preco }}€</p>
        <p class="text-white">Sales: {{ vendas }}</p>
        <p class="text-white">Area: {{ curso.area }}</p>
        <img src="{{ curso.image.url }}" height="200" width="200" alt="Imagem do curso">
        <h2 class="text-white mt-2">Contents</h2>
          {% if conteudos %}
          <ul class="text-white">
          {% for conteudo in conteudos %}
          <h2 class="text-white" sytle="font-size: 24px;" >{{ conteudo.title }}</h2>
            <a href="{{ conteudo.file.url }}" class="text-white"> Click to get the file</a>

          {% endfor %}
        </ul>

      {% else %}
        <p class="text-white">No content on this course yet.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

</body>
</html>

onlinecourses/cursos/templates/cursos/manageprofessors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% extends "./base.html" %}
{% block conteudo %}
<div class="container-form">
<div class="row">
   <h1>Manage Professors</h1>
{% if error_message %}
        <script>
        alert("{{ error_message }}");

    </script>

{% endif %}
</div>
 <div class="row text-align:center">
  <h2 style="color:white">Create Professor</h2>
 </div>

    <div class="row">

    <div    class="form-group">
  <form method="POST" action="{% url 'cursos:createprof' %}">
    {% csrf_token %}

        <div class="padding-top">
            <label for="emailcreate">Email:</label>

        </div>

            <input type="email" class="form-control" id="emailcreate" name="emailcreate">



        <div class="padding-top">
            <label for="username">Username:</label>

        </div>
            <input type="text"  class="form-control" name="username" id="username">




    <div class="padding-top">
        <label for="password">Password:</label>
    </div>
    <input type="password"  class="form-control  padding-top" name="password" id="password">
    <div class="padding-top">
        <button type="submit" class="form-button">Create Professor</button>
    </div>


  </form>
    </div>
</div>
<div class=" row">

    <div class="mt-5">

        <h2 style="color:white">Delete Professor</h2>
    </div>
    </div>
    <div class="row">

   <div class="form-goup">
  <form method="POST" action="{% url 'cursos:deleteprof' %}">
    {% csrf_token %}
       <div class="padding-top">
        <label for="emaildelete" class="form-lable">Email:</label>
       </div>
       <input type="email"  class="form-control" id="emaildelete" name="emaildelete">
       <div class="padding-top">
            <button type="submit" class="form-button">Delete Professor</button>
       </div>
  </form>
    </div>
         </div>
    <br>
{% endblock %}

</div>
</body>
</html>

onlinecourses/cursos/templates/cursos/meuscursos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My courses</title>

</head>
<body>
{% extends "./base.html" %}

{% block conteudo %}
<br>

\
<div class="container_cursos container">
    <div class="row" style="gap:10px">

        {% for curso in cursos %}
        <div class="card col-3 card-curso-view">
            <a class="text-decoration-none h-100 " href="{% url 'cursos:detalhe' curso.pk %}">
                <div class="card-body" style="background-image: url({{ curso.image.url }})">
                    <div class="card-body-content">
                        <h5 class="card-title">{{ curso.descricao }}</h5>

                    </div>
                </div>

            </a>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}
</body>
</html>

onlinecourses/cursos/templates/cursos/pagamento.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment</title>
     <style>
    form {
      max-width: 500px;
      margin: 0 auto;

    }
    input {
      display: block;
      width: 100%;
      margin-bottom: 10px;
      padding: 10px;
      border-radius: 5px;
      border: 1px solid #ccc;
      font-size: 16px;
    }
    button {
      display: block;
      margin: 0 auto;
      padding: 10px 20px;
      border-radius: 5px;
      border: none;
      background-color: #007bff;
      color: #fff;
      font-size: 16px;
      cursor: pointer;
    }
  </style>
</head>
<body>

{% extends "./base.html" %}
{% block conteudo%}
<div class="container d-flex justify-content-center align-items-center mt-5">
    <div class="col-md-6">
        <form action="{% url 'cursos:compra' curso.pk%}"
        method="post">
         {% csrf_token %}
        <label for="cardNumber">Card Number:</label>
        <input type="text" id="cardNumber" name="cardNumber" placeholder="1234 5678 9012 3456" maxlength="19" required>

        <label for="cardName">Name on Card:</label>
        <input type="text" id="cardName" name="cardName" placeholder="John Doe" required>

        <label for="expiryMonth">Expiry Month:</label>
        <input type="text" id="expiryMonth" name="expiryMonth" placeholder="10" maxlength="2" required>

        <label for="expiryYear">Expiry Year:</label>
        <input type="text" id="expiryYear" name="expiryYear" placeholder="2022" maxlength="4" required>



        <label for="cvv">CVV:</label>
        <input type="text" id="cvv" name="cvv" placeholder="123"  maxlength="3" required>

        <button class = "form-button" type="submit">Submit Payment</button>
      </form>

    <script>
            const cardNumberInput = document.getElementById('cardNumber');

            cardNumberInput.addEventListener('input', (e) => {
                const input = e.target.value;
                e.target.value = input.replace(/[\W\s\._\-]+/g, '').replace(/(\d{4})/g, '$1 ').trim();

            });

            const expiryMonthInput = document.getElementById("expiryMonth");
            expiryMonthInput.addEventListener("input", function() {
              // remover caracteres que não são números
              this.value = this.value.replace(/[^0-9]/g, "");

              // limitar o valor para ser entre 1 e 12
              const valueAsNumber = Number(this.value);
              if (valueAsNumber < 1 || valueAsNumber > 12) {
                this.setCustomValidity("Please enter a valid expiry month (1-12).");
              } else {
                this.setCustomValidity("");
              }
            });


            const expiryYearInput = document.getElementById("expiryYear");
            expiryYearInput.addEventListener("input", function() {

              this.value = this.value.replace(/[^0-9]/g, "");
            });





            const cvvInput = document.getElementById("cvv");
            cvvInput.addEventListener("input", function() {

              this.value = this.value.replace(/[^0-9]/g, "");



            });



        </script>

{% endblock %}
        </div>
    </div>
</body>
</html>